# 監聽埠
listener 1883

# [嚴謹] 關閉匿名連線
allow_anonymous false

# 指定密碼檔案路徑 (對應容器內的路徑)
password_file /mosquitto/config/passwd

# 資料持久化設定
persistence true
persistence_location /mosquitto/data/

# 日誌設定
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information