# ansible/roles/monitoring/handlers/main.yml


- name: Reload Prometheus
  uri:
    url: "http://localhost:9090/-/reload"
    method: POST
    status_code: [200, 202]
#  when: config_result.changed # TODO [法 1] 只有當設定檔真的有變動時才執行