# 定義來源格式
input {
  tcp {
    port => 5000
    codec => json # 自動把 Python 傳來的 metadata 轉成欄位
#    codec => plain {
#      charset => "UTF-8"
#    }
  }
}

# 日誌分類
filter {
  # 嘗試解析 JSON，如果失敗則保留原始文字在 message 欄位
#  json {
#    source => "message"
#    skip_on_invalid_json => true
#  }
#
#  # 如果解析失敗，標記一個 tag 方便之後在 Kibana 過濾
#  if "_jsonparsefailure" in [tags] {
#    mutate { add_field => { "log_status" => "malformed" } }
#  }

  # 1. 如果 Python 沒傳 app_name，給一個預設值防止歸類失敗
  if ![app_name] {
    mutate { add_field => { "app_name" => "unknown_python_app" } }
  }

  # 2. 自動修正索引名稱（選用）
  # 透過 app_name 來決定要把日誌存在哪個索引，方便管理
  mutate {
    lowercase => [ "app_name" ]
  }
}

# 定義輸出索引
output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    # 最佳實踐：按 app_name 拆分索引，這樣刪除舊資料時可以按 APP 刪
    index => "service-%{[app_name]}-%{+YYYY.MM.dd}"
#    user => "elastic"
#    password => "123456789"
  }

  # [除錯] 收到的東西直接印在 docker logs
  stdout { codec => rubydebug }
}