database:
  host: localhost
  database: pgdatabase
  user: oltp_user
  password: oltp_pwd

init_data:
  products: 8 # 建立已知訂單訊息
  machine_layout: # 建立已知訂單訊息機台
    L1: ["CNC","CNC","DRILL","LATHE","CNC","LATHE"]
    L2: ["CNC","DRILL","DRILL","LATHE","LATHE","CNC"]
    L3: ["CNC","CNC","CNC","DRILL","LATHE","LATHE"]

simulate:
  duration_hours: 24 # not used

  target_qty_min: 300 # 目標生産数の最小値
  target_qty_max: 1500 # 目標生産数の最大値

  prod_qty_min: 1 # 實際生產效率の最小値
  prod_qty_max: 3 # 實際生產效率の最大値

  orders: 30 # 初始第一批訂單有幾個

  status_types:
    - RUNNING
    - IDLE
    - DOWN
  event_types:
    - ERROR
    - MAINTENANCE
    - ALARM

load_profile: # 特殊時間紅利加成 + 訂單生成機率 (prob)
  OFF_PEAK:
    prod_per_sec: 1
    status_per_sec: 2
    event_per_sec: 0.2
    prob: 0.001

  NORMAL:
    prod_per_sec: 3
    status_per_sec: 6
    event_per_sec: 1
    prob: 0.003

  PEAK:
    prod_per_sec: 8
    status_per_sec: 15
    event_per_sec: 3
    prob: 0.006