database:
  host: localhost
  database: pgdatabase
  user: oltp_user
  password: oltp_pwd

init_data:
  products: 8
  machine_layout:
    L1: ["CNC","CNC","DRILL","LATHE","CNC","LATHE"]
    L2: ["CNC","DRILL","DRILL","LATHE","LATHE","CNC"]
    L3: ["CNC","CNC","CNC","DRILL","LATHE","LATHE"]

simulate:
  duration_hours: 24 # not used

  target_qty_min: 300 # 目標生産数の最小値
  target_qty_max: 1500 # 目標生産数の最大値

  orders: 30

  status_types:
    - RUNNING
    - IDLE
    - DOWN
  event_types:
    - ERROR
    - MAINTENANCE
    - ALARM

load_profile:
  OFF_PEAK:
    status_per_sec: 2
    production_per_sec: 1
    event_per_sec: 0.2
    prob: 0.001

  NORMAL:
    status_per_sec: 6
    production_per_sec: 3
    event_per_sec: 1
    prob: 0.003

  PEAK:
    status_per_sec: 15
    production_per_sec: 8
    event_per_sec: 3
    prob: 0.006