database:
  host: localhost
  database: pgdatabase
  user: oltp_user
  password: oltp_pwd

init_data:
  products: 8 # 建立已知訂單訊息
  machine_layout: # 建立已知機台訊息
    L1: ["CNC","CNC","DRILL","LATHE","CNC","LATHE"]
    L2: ["CNC","DRILL","DRILL","LATHE","LATHE","CNC"]
    L3: ["CNC","CNC","CNC","DRILL","LATHE","LATHE"]

simulate:
  orders: 108 # 第一批生產訂單數量

  target_qty_min: 1000 # 目標生産数の最小値
  target_qty_max: 5000 # 目標生産数の最大値

  prod_qty_min: 1 # 實際生產效率の最小値
  prod_qty_max: 5 # 實際生產效率の最大値

load_profile: # 訂單生成機率 (prob)
  OFF_PEAK:
    prob: 0.1
  NORMAL:
    prob: 0.5
  PEAK:
    prob: 1