name: ooud-cluster

include:
  - path: ./docker/airflow/docker-compose.yaml
  - path: ./docker/monitoring/docker-compose.yaml
  - path: ./docker/portainer/docker-compose.yaml
  - path: ./docker/postgresql/docker-compose.yaml
  - path: ./docker/iot-platform/mqtt-compose.yaml
  - path: ./docker/iot-platform/kafka-compose.yaml
  - path: ./docker/elk/docker-compose.yaml
#  - path: ./docker/powa/docker-compose.yaml