# ansible/roles/monitoring/task/main.yml


- name: Render Prometheus Configuration
  template:
    src: prometheus.yml.j2
    dest: '{{ config_path }}'
    # TODO 生成臨時檔案，用於檢查語法
    validate: "docker run --rm -v %s:/test.yml --entrypoint promtool prom/prometheus:latest check config /test.yml"

#  register: config_result  # TODO [法 1] 記錄檔案是否有變動
  notify: Reload Prometheus # TODO [法 2] 告知 handlers 進行 "Reload Prometheus" 動作


- name: Manual Force Reload Prometheus
  uri:
    url: "http://localhost:9090/-/reload"
    method: POST
    status_code: [200, 202]
  # never: 平時執行該任務會被自動跳過，除非明確指定
  # 明確指定 --tags reload 時才會跑
  tags: [never, reload]