mqtt:
  host: 127.0.0.1
  port: 1883
  acc: admin
  pwd: 123456789

kafka:
  host: 127.0.0.1
  port: 9092
  auto_offset_reset: earliest
  enable_auto_commit: false

database:
  host: 127.0.0.1
  port: 5432
  database: pgdatabase
  user: oltp_user
  password: oltp_pwd

init_data:
  products: 1 # 自動化生成訂單 ( 初始化 + 每周期機率 )
  machine_layout: # 建立已知機台訊息
    L1: ["CNC","CNC","DRILL","LATHE","CNC","LATHE"]
    L2: ["CNC","DRILL","DRILL","LATHE","LATHE","CNC"]
    L3: ["CNC","CNC","CNC","DRILL","LATHE","LATHE"]

simulate:
  batch_size: 500 # commit = WAL flush，若太頻繁 IO latency ↑

  orders: 10 # 第一批生產訂單數量

  target_qty_min: 500 # 目標生産数の最小値
  target_qty_max: 3000 # 目標生産数の最大値

  prod_qty_min: 1 # 實際生產效率の最小値
  prod_qty_max: 10 # 實際生產效率の最大値

load_profile:
  OFF_PEAK:
    efficiency: 1 # 2 # 效率加成 ( 增加數據筆數 )
    prob: 0.001 # 0.005 # 訂單生成機率
  NORMAL:
    efficiency: 3 # 5
    prob: 0.005 # 0.01
  PEAK:
    efficiency: 5 # 10
    prob: 0.05 # 0.1